### ISSUE TITLE
Add a recommendation about signatures

### ISSUE THREAD

**Issue by nathanmsmith** [makeitlegit/propername#15]
In my experience, I've found that using flexbox or similarly responsive design tools allow for accurate handling of longer signatures.

![FZRncJKVsAAIstn](https://user-images.githubusercontent.com/5677971/183565410-856f62aa-3489-42f2-ba9c-d2f118e03521.jpeg)

In cases where signature input is fixed, omitting middle names is an acceptable option. What's tricky is determining what a first and last name are. A naive approach would be to [split](http://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split) a name on spaces and then take the first and last elements of the resulting array. But this doesn't handle last names like `de la Cruz` where the last name is made up of multiple parts all separated by spaces. I don't have a great solution, would love to discuss more.

Initial only signatures can also be used in places. As @juliemeridian notes a good default may be single initial firstname + multiple initial last name.

**Comment by juliemeridian** [comment]
I got back around to updating ProperName and added a short section about initials that links back to this issue about ways to handle signatures. Thanks for the input!
