### ISSUE TITLE
Some names have apostrophes

### ISSUE THREAD

**Issue by toddobryan** [makeitlegit/propername#6]
My name is Todd O'Bryan.

That's O - apostrophe - capital B - R - Y - A - N.

The IRS refuses to allow an apostrophe and even though my original birth certificate had an apostrophe, a data migration in my home state removed it, something I didn't notice until I was applying for a passport and I had to request a corrected one. (Luckily they had the original to refer to and could determine the mistake was theirs.)

Here's what I have to deal with

Obryan
O'bryan
O&amp;#39;Bryan (this is the current form of my name when Amazon sends email)

This is especially bad because single quotes have special meaning in databases, so it's often the case that I can't enter the apostrophe when I'm entering my name. People also have trouble finding me, because I'm not sure if their system has retained the apostrophe or not, so they have to search for both O'BRYAN and OBRYAN.

Except that my credit card company decided to replace the apostrophe with a space, so it's Todd O Bryan, and I have to worry about being filed in the Bs.

Thanks for putting together this repo! :-)

**Comment by juliemeridian** [comment]
I got back around to updating ProperName and added an apostrophe detail that links back to this issue about database woes. Thanks for the input!
